Disabled the aspect of the thread-check logic at test tear down which was throwing an exception.  It will just log @ ERROR immediately if there are any threads which were not properly terminated.  I also moved the wait (for up to 2 seconds) for threads to terminate after the log @ ERROR.  My thinking is that waiting might make the initial conditions for the next test cleaner, but it does not excuse the current test from failing to terminate its threads.  Finally, I modified the message to include the test name (getName()) and the delegate class (getOurDelegate()).
I will note that the information coming out of the thread-check logic is not yet very good. For example, you can see in this message that it is complaining about the main thread!

ERROR: 8687      main com.bigdata.journal.ProxyTestCase.tearDown(ProxyTestCase.java:182): Threads left active after task: test=test_registerAndUse, delegate=com.bigdata.journal.TestWORMStrategy, startupCount=3, teardownCount=4, threads: Thread name=main


git-svn-id: https://svn.code.sf.net/p/bigdata/code/branches/QUADS_QUERY_BRANCH@4682 8f7bc0f5-282e-0410-95e3-8d296e9bb460