This is running against an embedded federation. Browsing through CI, it appears to fail occasionally and always at the same line.  Ok.  It appears that the test was running with two data services but it was assuming that there was only one data service. This could cause it to direct the wrong service to overflow, which would account for the test failure which was being reported.
junit.framework.AssertionFailedError: expected:<1> but was:<0>
	at com.bigdata.service.TestOverflow.test_register1ThenOverflow(TestOverflow.java:115)


git-svn-id: https://svn.code.sf.net/p/bigdata/code/branches/QUADS_QUERY_BRANCH@4757 8f7bc0f5-282e-0410-95e3-8d296e9bb460