Changes to the GATHER/PREPARE protocol in order to close some gaps introduced by the recent refactoring to handle a service that joins after the GATHER but before the PREPARE. {{{ - Modified the GatherTask to return the consensusReleaseTime. This   makes it possible to further validate things in Prepare2Phase.
- Modified the PREPARE message to include (a) whether the service
  participated in the GATHER; and (b) the consensusReleaseTime from
  the leader. This change is NOT backwards compatible. Migration
  requires that commits are suspended on the HA replication cluster
  during a rolling upgrade.  The decision to not provide backwards
  compatibility was made on the basis that we do not yet have a GA
  release with support for the HA replication cluster.

- Modified commitNow() to collect and pass along the set of joined
  services in the GATHER as well as in the PREPARE.

- Modified QuorumCommitImpl to pass along whether or not a service was
  joined in the GATHER as well as in the PREPARE and the consensus
  release time for the GATHER.

- Modified Prepare2Phase to check additional conditions based on
  whether the service participated in the GATHER and to verify the
  release time on the followers (must be consisent with the GATHER
  even if the follower joined after the GATHER).

- Modified HAJournal.config to use the FEDNAME environment variable.

- Updated comments in HAJournal.env.

- Isolated the FEDNAME as a static constant in the HA CI test suite.  

  ---- test results ----

- 2 unexpected failures. both are stochastic.

- testQuorumBreaksABC_failLeader: Failed once. Failed twice (uncurable
  service joined problem in seek consensus on C). 3rd time passed. 4th
  time passed.

java.lang.RuntimeException: java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at com.bigdata.io.TestCase3.assertCondition(TestCase3.java:233)
	at com.bigdata.journal.jini.ha.AbstractHA3JournalServerTestCase.awaitNextQuorumMeet(AbstractHA3JournalServerTestCase.java:2019)
	at com.bigdata.journal.jini.ha.TestHA3JournalServer.testQuorumBreaksABC_failLeader(TestHA3JournalServer.java:1329)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at com.bigdata.journal.jini.ha.AbstractHA3JournalServerTestCase$9.run(AbstractHA3JournalServerTestCase.java:2031)
	at com.bigdata.io.TestCase3.assertCondition(TestCase3.java:223)
	... 22 more
Caused by: java.util.concurrent.TimeoutException
	at com.bigdata.quorum.AbstractQuorum.awaitQuorum(AbstractQuorum.java:1159)
	at com.bigdata.journal.jini.ha.AbstractHA3JournalServerTestCase$9.run(AbstractHA3JournalServerTestCase.java:2022)
	... 23 more

- testABCMultiLoadFollowerReadsLargeLoad: Failed once (trace
  below). 2nd time passed.

java.util.concurrent.ExecutionException: com.bigdata.quorum.QuorumException: Quorum not met on token: expected 0, actual=1
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
	at java.util.concurrent.FutureTask.get(FutureTask.java:111)
	at com.bigdata.journal.jini.ha.TestHA3JournalServer.doABCMultiLoadFollowerReads2(TestHA3JournalServer.java:2015)
	at com.bigdata.journal.jini.ha.TestHA3JournalServer.testABCMultiLoadFollowerReadsLargeLoad(TestHA3JournalServer.java:1901)
Caused by: com.bigdata.quorum.QuorumException: Quorum not met on token: expected 0, actual=1
	at com.bigdata.quorum.AbstractQuorum.assertQuorum(AbstractQuorum.java:1065)
	at com.bigdata.quorum.AbstractQuorumClient.getLeader(AbstractQuorumClient.java:106)
	at com.bigdata.journal.jini.ha.AbstractHA3JournalServerTestCase$LargeLoadTask.call(AbstractHA3JournalServerTestCase.java:2312)
	at com.bigdata.journal.jini.ha.AbstractHA3JournalServerTestCase$LargeLoadTask.call(AbstractHA3JournalServerTestCase.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
}}}

@see https://sourceforge.net/apps/trac/bigdata/ticket/530 (Journal HA)

git-svn-id: https://svn.code.sf.net/p/bigdata/code/branches/READ_CACHE@7209 8f7bc0f5-282e-0410-95e3-8d296e9bb460